# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.ssh.insert_key = false
  config.vbguest.auto_update = true
  config.vm.box_check_update = false

  # create Management (mgmt) node
  config.vm.define "mgmt" do |mgmt_config|
  mgmt_config.vm.box = "ubuntu/bionic64"
  mgmt_config.vm.hostname = "mgmt"
  mgmt_config.vm.network "private_network", ip: "192.168.56.9"
  mgmt_config.vm.provider "virtualbox" do |vb|
    vb.name = "mgmt"
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    vb.memory = "512"
  end # of vb
  # Shared folders
  if Vagrant::Util::Platform.windows? then
    # Configuration SPECIFIC for Windows 10 hosts
    mgmt_config.vm.synced_folder "examples", "/home/vagrant/examples",
    id: "vagrant-root", ouner: "vagrant", group: "vagrant",
    mount_options: ["dmode=775", "fmode=664"]
  else
    # Configuration for Unix/Linux hosts
    mgmt_config.vm.synced_folder "examples", "/home/vagrant/examples",
    mount_options: ["dmode=775", "fmode=664"]
  end # of shared folders
  # Provisioning
  mgmt_config.vm.provision "shell", path: "bootstrap-mgmt.sh"
  end # of mgmt_config

  # create Hospital node
  config.vm.define "hosp" do |hosp_config|
    hosp_config.vm.box = "ubuntu/bionic64"
    hosp_config.vm.hostname = "hospital"
    hosp_config.vm.network "private_network", ip: "192.168.56.11"
    hosp_config.vm.provider "virtualbox" do |vb|
      vb.name = "hospital"
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.memory = "512"
    end # of vb
    # Provisioning
    config.vm.provision "shell", inline: <<-SHELL
      echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDZZr5NqMnX2oacqJCb/Wt/nMtpCvfytVo4GYZ3QA1ewD2Jjpg/t4Ti+n3d+jD3A2d5CLoY7ZowQTVFc013CpBLeb1QKaPEPxanU0tft9aoT+5jzbh73tJxU0zYOelcJdvqSkbBDLGHIyp0cOLDJQGWIiuU65IwWme3x8ZuF6XktY1JwO4Xdn2cucE5fzMh7bQe9mO/apR1dFtvvqZQCRbmTOv7aOwADiHhEamLgndHoAySakvq7qtRgmSP5mqDPqPXVbfirXzPfY8joMkb8qr0n39Yvra/ND5wWuKbA5LGH6Gtqm47wNjJHJuEEPZTjGrr83GCH82FS/9LsiLkJ6/1 alex@desktop" >> /home/vagrant/.ssh/authorized_keys
    SHELL
  # Shared folders
  if Vagrant::Util::Platform.windows? then
    # Configuration SPECIFIC for Windows 10 hosts
    hosp_config.vm.synced_folder "examples", "/home/vagrant/examples",
    id: "vagrant-root", ouner: "vagrant", group: "vagrant",
    mount_options: ["dmode=775", "fmode=775"]
  else
    # Configuration for Unix/Linux hosts
    hosp_config.vm.synced_folder "examples", "/home/vagrant/examples",
    mount_options: ["dmode=775", "fmode=775"]
  end # of shared folders
  end # of hosp

  # create Hospital Externalized Policies node
  config.vm.define "pdp" do |pdp_config|
    pdp_config.vm.box = "ubuntu/bionic64"
    pdp_config.vm.hostname = "pdp"
    pdp_config.vm.network "private_network", ip: "192.168.56.12"
    pdp_config.vm.provider "virtualbox" do |vb|
      vb.name = "pdp"
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.memory = "512"
    end # of vb
    config.vm.provision "shell", inline: <<-SHELL
      echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDZZr5NqMnX2oacqJCb/Wt/nMtpCvfytVo4GYZ3QA1ewD2Jjpg/t4Ti+n3d+jD3A2d5CLoY7ZowQTVFc013CpBLeb1QKaPEPxanU0tft9aoT+5jzbh73tJxU0zYOelcJdvqSkbBDLGHIyp0cOLDJQGWIiuU65IwWme3x8ZuF6XktY1JwO4Xdn2cucE5fzMh7bQe9mO/apR1dFtvvqZQCRbmTOv7aOwADiHhEamLgndHoAySakvq7qtRgmSP5mqDPqPXVbfirXzPfY8joMkb8qr0n39Yvra/ND5wWuKbA5LGH6Gtqm47wNjJHJuEEPZTjGrr83GCH82FS/9LsiLkJ6/1 alex@desktop" >> /home/vagrant/.ssh/authorized_keys
    SHELL
  # Shared folders
  if Vagrant::Util::Platform.windows? then
    # Configuration SPECIFIC for Windows 10 hosts
    pdp_config.vm.synced_folder "examples", "/home/vagrant/examples",
    id: "vagrant-root", ouner: "vagrant", group: "vagrant",
    mount_options: ["dmode=775", "fmode=775"]
  else
    # Configuration for Unix/Linux hosts
    pdp_config.vm.synced_folder "examples", "/home/vagrant/examples",
    mount_options: ["dmode=775", "fmode=775"]
  end # of shared folders
  end # of hosp

  # Create Labs Nodes 
  config.vm.define "lab" do |lab_config|
    lab_config.vm.box = "ubuntu/bionic64"
    lab_config.vm.hostname = "lab1"
    lab_config.vm.network "private_network", ip: "192.168.57.11"
    lab_config.vm.provider "virtualbox" do |vb|
      vb.name = "lab1"
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.memory = "512"
    end # of vb
    # Provisioning
    config.vm.provision "shell", inline: <<-SHELL
      echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDZZr5NqMnX2oacqJCb/Wt/nMtpCvfytVo4GYZ3QA1ewD2Jjpg/t4Ti+n3d+jD3A2d5CLoY7ZowQTVFc013CpBLeb1QKaPEPxanU0tft9aoT+5jzbh73tJxU0zYOelcJdvqSkbBDLGHIyp0cOLDJQGWIiuU65IwWme3x8ZuF6XktY1JwO4Xdn2cucE5fzMh7bQe9mO/apR1dFtvvqZQCRbmTOv7aOwADiHhEamLgndHoAySakvq7qtRgmSP5mqDPqPXVbfirXzPfY8joMkb8qr0n39Yvra/ND5wWuKbA5LGH6Gtqm47wNjJHJuEEPZTjGrr83GCH82FS/9LsiLkJ6/1 alex@desktop" >> /home/vagrant/.ssh/authorized_keys
    SHELL
  # Shared folders
  if Vagrant::Util::Platform.windows? then
    # Configuration SPECIFIC for Windows 10 hosts
    lab_config.vm.synced_folder "examples", "/home/vagrant/examples",
    id: "vagrant-root", ouner: "vagrant", group: "vagrant",
    mount_options: ["dmode=775", "fmode=775"]
  else
    # Configuration for Unix/Linux hosts
    lab_config.vm.synced_folder "examples", "/home/vagrant/examples",
    mount_options: ["dmode=775", "fmode=775"]
  end # of shared folders
  end

end # of config
