DROP TABLE IF EXISTS pendingtests;
DROP TABLE IF EXISTS tests;
DROP TABLE IF EXISTS labs;
DROP TABLE IF EXISTS patients;
DROP TABLE IF EXISTS employees;
DROP TABLE IF EXISTS roles;
DROP TABLE IF EXISTS token;
DROP TABLE IF EXISTS users;
